### ISSUE TITLE
Problems using stax-2 java 11

### ISSUE THREAD

**Issue by pavan2017** [FasterXML/stax2-api#19]
I have upgraded from java 8 to 11 and using woodstox 4.1.
```
public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) {
        try {
            XMLValidationSchemaFactory factory = XMLValidationSchemaFactory.newInstance(XMLValidationSchema.SCHEMA_ID_W3C_SCHEMA);
            XMLValidationSchema xmlValidationSchema = factory.createSchema(schemaResource.getURL());
            XMLInputFactory2 xmlFactory = (XMLInputFactory2) XMLInputFactory2.newInstance();
            InputStream xmlInputStream = xmlResource.getInputStream();
            XMLStreamReader2 reader = (XMLStreamReader2) xmlFactory.createXMLStreamReader(xmlInputStream);
            reader.validateAgainst(xmlValidationSchema);
            while (reader.hasNext()) {
                int eventType = reader.next();
            
            }
          } catch (Exception e) {
            throw new IllegalArgumentException("Error while validating " + xmlResource.getFilename(), e);
        }
        return RepeatStatus.FINISHED;
    }
```
The above was working for last 2 years with java 8. After i upgraded to java 11, i get the below error.
javax.xml.stream.FactoryConfigurationError: No XMLValidationSchemaFactory implementation class specified or accessible (via system property 'org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c', or service definition under 'META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c')

Am i missing something?

**Comment by cowtowncoder** [comment]
This is not the repository for Woodstox, but for Stax2 API which is implemented by Stax libraries such as Woodstox and Aalto. So please report against Woodstox (I think you filed an issue for it, so can just reopen it).
