### ISSUE TITLE
"procesing" should be "processing"

### ISSUE THREAD

**Issue by martindorey** [FasterXML/stax2-api#24]
The spelling mistake is here in README.md:

> Stax2 API is an extension to standard [Stax](http://en.wikipedia.org/wiki/StAX) API ("STandard Api for Xml procesing")

This native English speaker would put "the" before "standard" too.

> most of API

"the" API

> possible for Java Stax parser

"a" Java Stax parser, well, I imagine, not knowing anything about this project.  There are other arguably missing articles but, to be honest, I didn't notice any of the article issues until I came to submit this.  The spelling mistake, though, right at the start made me cringe.

**Comment by cowtowncoder** [comment]
Thanks, fixed. Going forward happy to merge PRs for similar problems.
"Procesing" is unusual one  for me -- articles I do miss consistently (my mother tongue does not have them :-/ ), but misspellings are less common.
