### ISSUE TITLE
Does stax2-api subdue stax-api ?

### ISSUE THREAD

**Issue by Maatary** [FasterXML/stax2-api#6]
Is there any consequence of adding stax2-api as dependency in an application with respect to the normal stax-api ? Does it replace it by virtue of something ? 

As soon as i add it as a dependency in an application that has dependency on stax-api (javax.xml.stream). My application use stax2-api. As the result it gets broken. It is an old application that i am customizing.

**Comment by cowtowncoder** [comment]
Stax2-api is an extension, implemented by some of leading stax libraries; namely Woodstox and Aalto.
It allows use of features that basic Stax API does not expose, such as base64 encoded binary content, as well as a set of commonly implemented configurability options.

But it should not really affect functionality of basic stax api; nor should addition of stax2-api break any existing code or deployment. It really quite literally is a set of interfaces/abstract classes; as well as partial implementations of said interfaces/classes, to simply writing a full stax2 implenentation.

Without more actual details of what is broken and how I am not sure I can help you further.
