### ISSUE TITLE
Is there a way to explicit instruct XMLValidator to not validate certain element?

### ISSUE THREAD

**Issue by Chandan83** [FasterXML/stax2-api#8]
The woodstox XMLValidator loads entire text content in memory even if the reader chunks into multiple text events. Please see https://github.com/FasterXML/woodstox/issues/32 for more details. Does it make sense to introduce a way to register elements, identified by qname, which should not be validated.

**Comment by cowtowncoder** [comment]
There is no mechanism for doing this, but you could file an issue against `Woodstox` to request implementation. I think that's where this belong, at least first: if it turns out something that might need / benefit from change to stax2 api, can then file separate issue here.
